export const ADD_UNWATCHEDMOVIE = "ADD_UNWATCHEDMOVIE";
export const DELETE_UNWATCHEDMOVIE = "DELETE_UNWATCHEDMOVIE";
export const ADD_WATCHEDMOVIE = "ADD_WATCHEDMOVIE";
export const DELETE_WATCHEDMOVIE = "DELETE_WATCHEDMOVIE";
export const WATCH_MOVIE = "WATCH_MOVIE";
export const UNWATCH_MOVIE = "UNWATCH_MOVIE";
export const FILTER_WATCHED = "FILTER_WATCHED";
export const FILTER_UNWATCHED = "FILTER_UNWATCHED";
